version: '3.7'
services:
  app:
    build: ../
    container_name: "app"
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.uri=mongodb://db:27017/analyzer
  mongodb:
    container_name: "db"
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
